CLASS zcl_abapgit_user_exit DEFINITION
  INHERITING FROM zcl_abapgit_exit_caller.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abapgit_user_exit IMPLEMENTATION.
ENDCLASS.
