CLASS zcl_abapgit_user_exit DEFINITION
  PUBLIC
  INHERITING FROM zcl_abapgit_exit_caller
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abapgit_user_exit IMPLEMENTATION.
ENDCLASS.
